### ISSUE TITLE
Exception has occurred: ValueError cannot reshape array of size 168 into shape (12,12)

### ISSUE THREAD

**Issue by Misjudgments** [robintwhite/word-search-ai#1]
I know it's quite an old repository but i am getting a bug and home anyone that sees this can help me
after running the app and pressing "S"

i am getting this error on line 184
Exception has occurred: ValueError
cannot reshape array of size 168 into shape (12,12)
the line:
"letters_array = np.reshape(letters_array, (dim, dim))"

Please help!
@robintwhite

**Comment by robintwhite** [comment]
Can you share the link to the Wordsearch you are using? or provide a screenshot?
As with the notes on the README for the repo
**_Any errors, re-try by making Wordsearch window full-screen. It may have trouble finding the grid, as this is done automatically.
Must be square. Not tested on other Wordsearch sites_**
Please make a request for a non-square grid handle if you can please provide an example to the wordsearch used

**Comment by Misjudgments** [comment]
The wordsearch i used is:
https://thewordsearch.com/puzzle/149/harry-potter/
and just wanted to show more of the error so here:
https://prnt.sc/2104ro4
just wanted to say, when i changed the DIM, DIM to 14, 12 it worked but the next one had the same problem the cents_array

as for the non-square grid handle i don't know what that means so sorry.
(English is not my main language and kinda new to python so both together is hard)

**Comment by robintwhite** [comment]
@Misjudgments thanks for the information - right now the search is limited to a square array meaning it needs to be of dimensions of equal length (12,12) for example. This is the error I think you are seeing. I thought all the searches on this site were square so that is an oversight. I will close this issue and open a request for the non-square array. Apologies for the issue but thanks for being interested and I will try to implement a fix soon!
